// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzP-ag5DurV6HELAnVe28hRxfxnjC5nPo',
    appId: '1:403215412284:web:e2ec57137639357d9d6739',
    messagingSenderId: '403215412284',
    projectId: 'kamagi-99e91',
    authDomain: 'kamagi-99e91.firebaseapp.com',
    storageBucket: 'kamagi-99e91.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR7DXLquxraNHTSkbixp62-ofr1aU8UsE',
    appId: '1:403215412284:android:8adf8a3b89bfa73a9d6739',
    messagingSenderId: '403215412284',
    projectId: 'kamagi-99e91',
    storageBucket: 'kamagi-99e91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUyN0o0aRy_XMTCUV-YQu7lkx-ZGZhyjE',
    appId: '1:403215412284:ios:9bc4dcea04e09ab69d6739',
    messagingSenderId: '403215412284',
    projectId: 'kamagi-99e91',
    storageBucket: 'kamagi-99e91.appspot.com',
    iosBundleId: 'com.example.nathaniCat03',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUyN0o0aRy_XMTCUV-YQu7lkx-ZGZhyjE',
    appId: '1:403215412284:ios:9bc4dcea04e09ab69d6739',
    messagingSenderId: '403215412284',
    projectId: 'kamagi-99e91',
    storageBucket: 'kamagi-99e91.appspot.com',
    iosBundleId: 'com.example.nathaniCat03',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzP-ag5DurV6HELAnVe28hRxfxnjC5nPo',
    appId: '1:403215412284:web:306f2bcddba7053b9d6739',
    messagingSenderId: '403215412284',
    projectId: 'kamagi-99e91',
    authDomain: 'kamagi-99e91.firebaseapp.com',
    storageBucket: 'kamagi-99e91.appspot.com',
  );
}
